github:
  zip_url: http://example.com/download.zip
  another_url: another value
title: Karl Machleidt
logo: /assets/img/logo.png
description: Catch you on the bit side.
linkedin: true
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
